#!/usr/bin/bash
#
#
riverctl spawn --user set-environment XDG_CURRENT_DESKTOP=river
riverctl spawn "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
# riverctl spawn "systemctl --user restart xdg-desktop-portal"
riverctl spawn "systemd-inhibit --what=handle-power-key sleep infinity &"

riverctl keyboard-layout -options "ctrl:nocaps" "us(altgr-intl)" 

###KEYBINDINGS
# riverctl map normal Super+Control R spawn "$HOME/.config/river/init" #reload

riverctl map normal Super Return spawn "foot"
riverctl map normal Super D spawn "fuzzel"

riverctl map normal Super B spawn "qutebrowser"
riverctl map normal Super+Shift E spawn "emacsclient -c --alternate-editor="
riverctl map normal Super E spawn "emacs"
riverctl map normal Super V spawn "cliphist list | fuzzel --dmenu | cliphist decode | wl-copy"
riverctl map normal Super+Control V spawn "cliphist list | fuzzel --dmenu | cliphist delete"

riverctl map normal Super+Control P spawn "leaveriv.sh"
riverctl map normal Super+Control I spawn "iwd-demnu.sh"
riverctl map normal Super+Control O spawn "dmenu-bluetooth.sh"
riverctl map normal Super+Control T spawn "dbusmenu.py"

riverctl map normal Super P spawn "foot spotify_player"

riverctl map normal Super+Control U spawn "foot paru"

riverctl map normal Super N spawn 'fnottctl dismiss'

riverctl map normal Super S spawn "wlr-which-key ~/.config/wlr-which-key/spotlight.yaml"
riverctl map normal Super Print spawn "wlr-which-key ~/.config/wlr-which-key/screenshot.yaml"

riverctl map normal Super+Control M  spawn "UDISKIE_DMENU_LAUNCHER='fuzzel' udiskie-dmenu --dmenu"
riverctl map normal None XF86PowerOff spawn "leaveriv.sh"

riverctl map normal None Print spawn 'grim -g "$(slurp)" - | wl-copy'




riverctl spawn '/home/phil/.local/bin/inhibit-bridge'
riverctl map normal Super+Control Y spawn 'killall -USR1 inhibit-bridge'

riverctl declare-mode screenshot


riverctl input pointer-1739-52972-VEN_06CB:00_06CB:CEEC_Touchpad events disabled-on-external-mouse

riverctl map normal Super+Control K spawn 'toggle_lapkey.sh'

# Super+Q to close the focused view
riverctl map normal Super+Shift Q close

riverctl hide-cursor when-typing enabled 

# Super+Shift+E to exit river
riverctl map normal Super+Control E 

# Super+J and $mod+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous


# Super+Shift+J and $mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and $mod+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
# riverctl map normal Super Return zoom

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags

all_tags=$(((1 << 32) - 1))

# Super+Space to toggle float
riverctl map normal Super+Shift F toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super+Shift Space toggle-fullscreen

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal
# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
#
riverctl spawn 'wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 65%'

for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
 

    riverctl map $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+; echo wpctl get-volume@DEFAULT_AUDIO_SINK@ > /tmp/wobpipe '
    riverctl map $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
    riverctl map $mode None XF86AudioMicMute      spawn 'wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle'

    riverctl map $mode Super XF86AudioRaiseVolume  spawn 'playerctl next'
    riverctl map $mode Super XF86AudioLowerVolume  spawn 'playerctl previous'
    riverctl map $mode Super XF86AudioMute         spawn 'playerctl play-pause'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
riverctl border-color-focused "0x006800"
riverctl border-color-unfocused "0x404148"
riverctl border-color-urgent "0xa60000" #red
riverctl background-color "0xffffff" 
# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add ssd
riverctl rule-add -app-id 'Firefox' -title 'About Mozilla Firefox' float

riverctl rule-add -app-id "Zoom Workplace" float
riverctl rule-add -app-id "Zoom Workplace" -title "Meeting" no-float
riverctl rule-add -app-id "Zoom Workplace" -title "Zoom Workplace - Licensed account" no-float
riverctl rule-add -app-id "Zoom Workplace" -title "as_toolbar" tags all_tags

# River will send the process group of the init executable SIGTERM on exit.
riverctl map normal Super up    send-layout-cmd wideriver "--layout monocle"
riverctl map normal Super down  send-layout-cmd wideriver "--layout wide"
riverctl map normal Super left  send-layout-cmd wideriver "--layout left"
riverctl map normal Super right send-layout-cmd wideriver "--layout right"

# riverctl map normal Super Space send-layout-cmd wideriver "--layout-toggle"

riverctl map normal Super plus  send-layout-cmd wideriver "--ratio +0.025"
riverctl map normal Super equal send-layout-cmd wideriver "--ratio 0.5"
riverctl map normal Super minus send-layout-cmd wideriver "--ratio -0.025"

riverctl map normal Alt plus  send-layout-cmd wideriver "--count +1"
riverctl map normal Alt equal send-layout-cmd wideriver "--count 1"
riverctl map normal Alt minus send-layout-cmd wideriver "--count -1"

# riverctl map normal Alt e     send-layout-cmd wideriver "--stack even"
# riverctl map normal Alt w     send-layout-cmd wideriver "--stack dwindle"
# riverctl map normal Alt i     send-layout-cmd wideriver "--stack diminish"

riverctl map normal Super+Shift W send-layout-cmd wideriver "--layout wide --stack diminish --count 1 --ratio 0.4"
riverctl map normal Super+Shift D send-layout-cmd wideriver "--layout left --stack diminish --count 1 --ratio 0.5"
riverctl map normal Super+Shift M send-layout-cmd wideriver "--layout  monocle"

riverctl map normal Super+Shift T attach-mode top 
riverctl map normal Super+Shift B attach-mode bottom 

###AUTOSTART
riverctl spawn "~/.config/river/autostart"


riverctl attach-mode bottom
riverctl default-layout wideriver
wideriver \
  --layout                       monocle        \
  --layout-alt                   left     \
  --stack                        dwindle     \
  --count-master                 1           \
  --ratio-master                 0.50        \
  --count-wide-left              0           \
  --ratio-wide                   0.35        \
  --no-smart-gaps                            \
  --inner-gaps                   0           \
  --outer-gaps                   0           \
  --border-width                 1           \
  --border-width-monocle         0           \
  --border-width-smart-gaps      0           \
  --border-color-focused         "0x000000"  \
  --border-color-focused-monocle "0x000000"  \
  --border-color-unfocused       "0xFFFFFF"  \
  --log-threshold                info        \
